### ISSUE TITLE
測試案例

### ISSUE THREAD

**Issue by jimmyhealer** [ScafTeam/scaf-backend#17]
- [x] 欄位沒有正確輸入，例如缺少欄位等
- [x] 創建專案名稱是否唯一
- [x] 專案名稱不能有特殊字元，不能有 ```/ \ ? % * : | \ " < >``` 
- [x] 沒有判斷 專案名稱是否存在
- [x] 刪除專案沒有同時刪除看板
- [x] 刪除專案時，使用者也應該要清除 projects 資料

**Comment by jimmyhealer** [comment]
@0-ch

**Comment by 0-ch** [comment]
這些是要寫在測試案例裡的?
