### ISSUE TITLE
PUT POST DELETE PUT的request格式錯誤

### ISSUE THREAD

**Issue by Timyu0527** [ScafTeam/scaf-backend#23]
1. user data update可以接受以下request來更新使用者資料
```json
{
    "oldPassword": "[old password]",
    "newPassword": "[new password]"
}
```
2. PUT POST DELETE PUT的request有多餘的欄位狀態依然200或201

**Comment by jimmyhealer** [comment]
`PUT POST DELETE PUT的request有多餘的欄位狀態依然200或201`

不會有問題，因此不做修改

**Comment by jimmyhealer** [comment]
空請求正確
